---
title: "Discover Songs in Spotify"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(shiny)
library(shinythemes)
library(rsconnect)
library(DT)
library(dplyr)

fluidPage(theme = shinytheme("darkly"))
```

```{r}
spotify_data = 
  readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv') |>
  distinct(track_id, .keep_all = TRUE) |>
  dplyr::select(-track_id, -track_album_id, -playlist_id) |>
  mutate(track_album_release_year = as.numeric(str_sub(track_album_release_date, 1, 4))) |>
  dplyr::select(-track_album_release_date) |>
  mutate(
    popularity=track_popularity,
    playlist_name = factor(playlist_name),
    genre = factor(playlist_genre),
    subgenre = factor(playlist_subgenre)
  ) |>
  mutate(
    danceability = danceability * 100,
    energy = energy * 100
  ) |>
  mutate(
    key = factor(case_match(
      key,
      0 ~ "C", 1 ~ "C#/Db", 2 ~ "D",
      3 ~ "D#/Eb", 4 ~ "E", 5 ~ "F",
      6 ~ "F#/Gb", 7 ~ "G", 8 ~ "G#/Ab",
      9 ~ "A", 10 ~ "A#/Bb", 11 ~ "B"
    )),
    mode = factor(case_match(
      mode,
      0 ~ "Minor",
      1 ~ "Major"
    )),
    speechiness = factor(case_when(
      speechiness < 0.33 ~ "non-speech-like music",
      speechiness >= 0.33 & speechiness <= 0.66 ~ "mix of speech and music",
      speechiness > 0.66 ~ "entirely of spoken words"
    ))
  )



numeric_data <- spotify_data |>
  pivot_longer(
    cols = c(danceability, energy, loudness, acousticness, instrumentalness, liveness, valence, tempo, duration_ms
),
    names_to = "factor",
    values_to = "value"
  )

factor_data <- spotify_data |>
  pivot_longer(
    cols = c(key, mode, speechiness),  
    names_to = "factor",
    values_to = "content"
  )

sum_data <- bind_rows(
  numeric_data,
  factor_data
)



```



Column {.sidebar}
-----------------------------------------------------------------------

Hi there, music lovers~

Here you can explore how song popularity is distributed within a chosen musical genre, examine the distribution of a chosen musical feature within a selected genre and analyze song features for a specific artist.

Try to select your favorite genre and your go-to singer to begin with!


```{r}
genre_choices = 
	spotify_data |> 
	distinct(genre) |> 
	pull(genre)

selectInput(
	inputId = "genre_choice", 
	label = h3("Select Genre"), 
	choices = genre_choices,
	selected = "Pop"
)
```

```{r}
factor_choices = 
	sum_data |> 
	distinct(factor) |> 
	pull(factor)

selectInput(
	inputId = "factor_choice", 
	label = h3("Select Factor"), 
	choices = factor_choices,
	selected = "Danceability"
)
```

```{r}
max_pop = spotify_data |> pull(popularity) |> max()

sliderInput(
	inputId = "popularity_range",
	label = h3("Select Popularity Range"), 
	min = 0, 
	max = max_pop, 
	value = c(50, 90)
)
```

```{r}
textInput(
  inputId = "artist_choice",
  label = h3("Enter Artist Name"),
  value = "Maroon 5"
)

```


Column {data-width=250}
-----------------------------------------------------------------------

### Popularity Distribution for Selected Genre

```{r}
renderPlotly(
	spotify_data  |> 
		filter(
  		genre == input[["genre_choice"]], 
  		popularity %in% input[["popularity_range"]][1]:input[["popularity_range"]][2]
  	) |> 
		mutate(subgenre = fct_reorder(subgenre, popularity)) |> 
		plot_ly(x = ~subgenre, y = ~popularity, color= ~subgenre, type = "box")
)

```

### Selected Factor Distribution for Selected Genre

```{r}
renderPlotly({
  filtered_data <- sum_data |> 
    filter(
      genre == input[["genre_choice"]],
      factor == input[["factor_choice"]]
    )
  
  if (input[["factor_choice"]] %in% c("key", "mode", "speechiness")) {
    plot_data <- filtered_data |> 
      group_by(content) |> 
      summarise(count = n(), .groups = "drop") 

    plot_ly(
      plot_data,
      x = ~content,
      y = ~count,
      type = "bar",
      name = "Count"
    )
  } else {
    plot_ly(
      filtered_data,
      x = ~value,
      type = "histogram",
      name = "Value Distribution"
    )
  }
})

```

Column {data-width=250}
-----------------------------------------------------------------------

### Most Popular Songs in the Selected Genre

```{r}
filtered_data <- reactive({
    spotify_data |>
      filter(genre == input[["genre_choice"]]) |>
      arrange(desc(popularity))  
  })

renderDataTable({
    datatable(
      filtered_data(),
      options = list(
        pageLength = 10,   
        autoWidth = TRUE   
      ),
      rownames = FALSE     
    )
  })
```

### Song Features for the Selected Artist

```{r}
renderPlotly(
  sum_data |> 
    filter(
      factor ==input[["factor_choice"]],
      track_artist == input[["artist_choice"]]) |> 
   plot_ly(
      x = if (input[["factor_choice"]] %in% c("key", "mode", "speechiness")) {
        ~content
      } else {
        ~value
      },
      y = ~popularity,
      type = "scatter",
      mode = "markers",
      colors="pal",
      marker = list(size = 10)
    ) 
)

```




